# Generated by Django 3.0 on 2019-05-10 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='research',
            fields=[
                ('researchId', models.AutoField(primary_key=True, serialize=False)),
                ('researchType', models.TextField(choices=[('STRMN', 'Streaming'), ('SCRNM', 'By Screen name'), ('HASHT', 'By hashtags'), ('KEYWR', 'by keywords')], max_length=5)),
                ('researchDate', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 1, 52, 32, 979182, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='offStreamResearch',
            fields=[
                ('research_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.research')),
                ('startDate', models.DateField(default=datetime.datetime(2019, 5, 10, 1, 52, 32, 994800, tzinfo=utc))),
                ('endDate', models.DateField(default=datetime.datetime(2019, 5, 10, 1, 52, 32, 994800, tzinfo=utc))),
            ],
            bases=('search.research',),
        ),
        migrations.CreateModel(
            name='streamingResearch',
            fields=[
                ('research_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.research')),
                ('keywords', models.TextField(max_length=100)),
            ],
            bases=('search.research',),
        ),
        migrations.CreateModel(
            name='researchByHashtags',
            fields=[
                ('offstreamresearch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.offStreamResearch')),
                ('hashtags', models.TextField(default='2', max_length=100)),
            ],
            bases=('search.offstreamresearch',),
        ),
        migrations.CreateModel(
            name='researchByKeywords',
            fields=[
                ('offstreamresearch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.offStreamResearch')),
                ('keywords', models.TextField(default='3', max_length=100)),
            ],
            bases=('search.offstreamresearch',),
        ),
        migrations.CreateModel(
            name='researchByScreenName',
            fields=[
                ('offstreamresearch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.offStreamResearch')),
                ('screenName', models.TextField(default='1', max_length=100)),
            ],
            bases=('search.offstreamresearch',),
        ),
    ]
