# Generated by Django 3.0 on 2019-05-10 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190510_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='researchType',
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 11, 49, 37, 66158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 11, 49, 37, 66158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 11, 49, 37, 50536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchbyhashtags',
            name='hashtags',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='researchbykeywords',
            name='keywords',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='researchbyscreenname',
            name='screenName',
            field=models.TextField(default='', max_length=100),
        ),
    ]
