# Generated by Django 3.0 on 2019-05-10 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190510_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='researchByKeywords',
            new_name='ByHashtags',
        ),
        migrations.RenameModel(
            old_name='researchByHashtags',
            new_name='ByKeywords',
        ),
        migrations.RenameModel(
            old_name='researchByScreenName',
            new_name='ByScreenName',
        ),
        migrations.RemoveField(
            model_name='byhashtags',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='bykeywords',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='byhashtags',
            name='hashtags',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bykeywords',
            name='keywords',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 12, 3, 41, 68794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 12, 3, 41, 68794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 12, 3, 41, 68794, tzinfo=utc)),
        ),
    ]
