# Generated by Django 3.0 on 2019-05-10 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190510_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='byhashtags',
            options={'verbose_name': 'Research by hashtags', 'verbose_name_plural': 'Researches by hashtags'},
        ),
        migrations.AlterModelOptions(
            name='bykeywords',
            options={'verbose_name': 'Research by keywords', 'verbose_name_plural': 'Researches by keywords'},
        ),
        migrations.AlterModelOptions(
            name='byscreenname',
            options={'verbose_name': 'Research by screen name', 'verbose_name_plural': 'Researches by screen name'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['researchDate'], 'verbose_name': 'Research', 'verbose_name_plural': 'Researches'},
        ),
        migrations.AlterModelOptions(
            name='streamingresearch',
            options={'verbose_name': 'Streaming research', 'verbose_name_plural': 'Streaming researches'},
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 21, 12, 53, 771817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 21, 12, 53, 771817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 21, 12, 53, 767823, tzinfo=utc)),
        ),
    ]
