# Generated by Django 3.0 on 2019-05-10 23:59

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20190511_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingresearch',
            name='streamingDuration',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 23, 59, 11, 200188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 23, 59, 11, 200188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 23, 59, 11, 199191, tzinfo=utc)),
        ),
    ]
