# Generated by Django 3.0 on 2019-05-11 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20190511_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='limitTweetsNumber',
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 0, 3, 19, 90833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 0, 3, 19, 90833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 0, 3, 19, 89835, tzinfo=utc)),
        ),
    ]
