# Generated by Django 3.0 on 2019-05-11 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20190511_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='NumberOfTweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 18, 22, 37, 552291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 18, 22, 37, 552291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 18, 22, 37, 551251, tzinfo=utc)),
        ),
    ]
