# Generated by Django 3.0 on 2019-05-11 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20190511_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='NumberOfTweets',
            new_name='numberOfTweets',
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 21, 26, 9, 407798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 21, 26, 9, 407798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 21, 26, 9, 407798, tzinfo=utc)),
        ),
    ]
