# Generated by Django 3.0 on 2019-05-11 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20190511_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 22, 40, 2, 9340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 22, 40, 2, 9340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 22, 40, 2, 9340, tzinfo=utc)),
        ),
    ]
