# Generated by Django 3.0 on 2019-05-12 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20190511_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(unique=True)),
                ('name', models.TextField(default='')),
                ('screenName', models.TextField(default='')),
                ('followers_count', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('favorites_count', models.IntegerField(default=0)),
                ('statuses_count', models.IntegerField(default=0)),
                ('language', models.TextField(default='')),
                ('locationUser', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 22, 16, 5, 383931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 22, 16, 5, 383931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 22, 16, 5, 383931, tzinfo=utc)),
        ),
    ]
