# Generated by Django 3.0 on 2019-05-12 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20190512_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.TextField(default='', primary_key=True, serialize=False)),
                ('tweetPlace', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 22, 16, 25, 918424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 22, 16, 25, 918424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 22, 16, 25, 914427, tzinfo=utc)),
        ),
    ]
