# Generated by Django 3.0 on 2019-05-12 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20190512_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 22, 19, 22, 116000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 22, 19, 22, 116000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 22, 19, 22, 116000, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetId', models.TextField(unique=True)),
                ('text', models.TextField(default='', max_length=281)),
                ('source', models.TextField(max_length=60)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Location')),
            ],
        ),
    ]
