# Generated by Django 3.0 on 2019-05-12 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_auto_20190512_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='researchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Stream'), (2, 'OffStream')], default=1, max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 22, 58, 57, 155308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 22, 58, 57, 155308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 22, 58, 57, 155308, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='research',
            name='researchType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.researchType'),
            preserve_default=False,
        ),
    ]
