# Generated by Django 3.0 on 2019-05-12 23:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_auto_20190513_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchtype',
            options={'verbose_name': 'Research Type'},
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 23, 18, 52, 845618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 12, 23, 18, 52, 845618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 23, 18, 52, 845618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchtype',
            name='type',
            field=models.CharField(choices=[('Stream', 'Stream'), ('OffStream', 'OffStream')], default='S', max_length=10),
        ),
    ]
