# Generated by Django 3.0 on 2019-05-13 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0034_auto_20190513_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='resultsFile',
            field=models.FileField(default='static/scripts/Twitter_stream/collected_data/default.json', upload_to='static/scripts/Twitter_stream/collected_data/results_<django.db.models.fields.AutoField>.json'),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 13, 21, 6, 7, 540888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 13, 21, 6, 7, 540888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 6, 7, 540888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.researchType'),
        ),
    ]
