# Generated by Django 3.0 on 2019-05-13 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0036_auto_20190513_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='resultsFile',
        ),
        migrations.AddField(
            model_name='research',
            name='resultsFileName',
            field=models.TextField(default='static/scripts/Twitter_stream/collected_data/default.json'),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 13, 21, 23, 44, 488697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 13, 21, 23, 44, 488697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 23, 44, 488697, tzinfo=utc)),
        ),
    ]
