# Generated by Django 3.0 on 2019-05-18 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0045_auto_20190514_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offstreamresearch',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='offstreamresearch',
            name='startDate',
        ),
        migrations.AddField(
            model_name='offstreamresearch',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offstreamresearch',
            name='since',
            field=models.DateField(default=datetime.datetime(2019, 5, 18, 23, 42, 56, 433287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 23, 42, 56, 433287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='resultsFileName',
            field=models.TextField(default='static/collected_data/default.json'),
        ),
    ]
