# Generated by Django 3.0 on 2019-05-19 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0047_auto_20190519_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='byhashtags',
            old_name='hashtags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='since',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 20, 10, 0, 498647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 20, 10, 0, 498647, tzinfo=utc)),
        ),
    ]
