# Generated by Django 3.0 on 2019-05-19 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0048_auto_20190519_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offstreamresearch',
            name='since',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 21, 6, 57, 312386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 21, 6, 57, 311326, tzinfo=utc)),
        ),
    ]
