# Generated by Django 3.0 on 2019-05-19 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0050_auto_20190519_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offstreamresearch',
            name='since',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 22, 12, 14, 88853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 22, 12, 14, 87855, tzinfo=utc)),
        ),
    ]
