# Generated by Django 3.0 on 2019-05-23 02:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0052_auto_20190520_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offstreamresearch',
            name='since',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 2, 19, 46, 897091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 2, 19, 46, 897091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='streamingresearch',
            name='keywords',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='streamingresearch',
            name='streamingDuration',
            field=models.IntegerField(default=5),
        ),
    ]
