# Generated by Django 3.0 on 2019-05-23 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0053_auto_20190523_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byhashtags',
            name='tag',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bykeywords',
            name='keywords',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='byscreenname',
            name='screen',
            field=models.TextField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='since',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 23, 2, 24, 36, 810420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 2, 24, 36, 810420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='streamingresearch',
            name='streamingDuration',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
