# Generated by Django 3.0 on 2019-05-30 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0059_auto_20190529_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedTweets',
            fields=[
                ('research_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.research')),
                ('jsonFile', models.FileField(default='', upload_to='static/uploaded_data/')),
                ('description', models.TextField(default='')),
            ],
            bases=('search.research',),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='since',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 30, 21, 49, 2, 891332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 21, 49, 2, 891332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='researchtype',
            name='type',
            field=models.CharField(choices=[('Stream', 'Stream'), ('OffStream', 'OffStream'), ('Upload', 'Upload')], default='Stream', max_length=10),
        ),
    ]
