# Generated by Django 3.0 on 2019-05-31 22:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0065_auto_20190531_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='executionDuration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='offstreamresearch',
            name='since',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 31, 22, 58, 45, 680882, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='research',
            name='researchDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 22, 58, 45, 680882, tzinfo=utc)),
        ),
    ]
